### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by Rodrigo-Barros** [asiniy/sexy_lcd_clock#1]
Hi i really appreciate your dedication to made this extension but you could put an option to set clock to 24 hours? and if was possible editing the position them in screen?
Sorry for bad English.

**Comment by asiniy** [comment]
Hey, @Rodrigo-Barros 
Thanks for using this plugin. Those are good proposals, but I don't have enough time to implement. I'll be happy if you'd implement these 2 features

**Comment by Rodrigo-Barros** [comment]
I really would like to add these two features to your extension but in the middle of development, I found an problem these two features are more hard than though to add than I though, because to set the value for 24 clock I can't return the value to for your function formartTime(), because I don't understand the concept of promises. The Firefox api uses promises for almost all methods.
